vdw: # Van der Waals radii obtained from here: https://periodictable.com/Properties/A/VanDerWaalsRadius.v.html and formatted using Warp AI
  H: 1.20
  Zn: 1.39
  He: 1.40
  Cu: 1.40
  F: 1.47
  O: 1.52
  Ne: 1.54
  N: 1.55
  Hg: 1.55
  Cd: 1.58
  Ni: 1.63
  Pd: 1.63
  Au: 1.66
  C: 1.70
  Ag: 1.72
  Mg: 1.73
  Cl: 1.75
  Pt: 1.75
  P: 1.80
  S: 1.80
  Li: 1.82
  As: 1.85
  Br: 1.85
  U: 1.86
  Ga: 1.87
  Ar: 1.88
  Se: 1.90
  In: 1.93
  Tl: 1.96
  I: 1.98
  Kr: 2.02
  Pb: 2.02
  Te: 2.06
  Si: 2.10
  Xe: 2.16
  Sn: 2.17
  Na: 2.27
  K: 2.75

cov: #covalent radius taken from here https://periodictable.com/Properties/A/CovalentRadius.v.html and formatted using Warp AI
  Br: 1.20
  Al: 1.21
  Zn: 1.22
  Ga: 1.22
  Ni: 1.24
  Co: 1.26
  Li: 1.28
  Fe: 1.32
  Cu: 1.32
  Hg: 1.32
  Pt: 1.36
  Au: 1.36
  Te: 1.38
  Cr: 1.39
  Mn: 1.39
  Pd: 1.39
  Sn: 1.39
  Sb: 1.39
  I: 1.39
  Xe: 1.40
  Po: 1.40
  Mg: 1.41
  Nb: 1.64
  Na: 1.66
  Cm: 1.69
  Sc: 1.70
  Ta: 1.70
  Zr: 1.75
  Hf: 1.75
  Ca: 1.76
  Am: 1.80
  Yb: 1.87
  Lu: 1.87
  Pu: 1.87
  Er: 1.89
  Y: 1.90
  Tm: 1.90
  Np: 1.90
  Dy: 1.92
  Ho: 1.92
  Tb: 1.94
  Sr: 1.95
  Gd: 1.96
  U: 1.96
  Ar: 1.06
  As: 1.19
  Be: 0.96
  B: 0.85
  C: 0.76
  Cl: 1.02
  F: 0.57
  Ge: 1.2
  He: 0.28
  H: 0.31
  Kr: 1.16
  Ne: 0.58
  N: 0.71
  O: 0.66
  P: 1.07
  Si: 1.11
  Se: 1.2
  S: 1.05
  